name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  cicd:
    uses: jo-jee/workflows/.github/workflows/k8s-cicd.yml@main
    with:
      repo: web-blog
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
